[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "renovate-pdm-groups-issue-sub-directory"
version = "0.1.0"
description = ""
authors = []
requires-python = ">=3.11"
dependencies = [
    "httpx==0.24.0",
    "pytest==7.3.1",
]
